const imgUrl = "ee03_ow_tnb_pl2/images/";
const soundUrl = "ee03_ow_tnb_pl2/sounds/";
const lottieUrl = "ee03_ow_tnb_pl2/lottie/";

const IntroMap = {
  id: "Scene22",

  Bg: `${imgUrl}texture_bg_dark.svg`,

  sprites: [
    `${imgUrl}organs/eye.svg`,
    `${imgUrl}organs/nose.svg`,
    `${imgUrl}organs/ear.svg`,
    `${imgUrl}organs/tongue.svg`,
    `${imgUrl}organs/touch.svg`,
    `${imgUrl}game2_images/eye/rainbow_eye.svg`,
    `${imgUrl}game2_images/nose/flower_nose.svg`,
    `${imgUrl}game2_images/ear/speakers_ear.svg`,
    `${imgUrl}game2_images/tongue/cup_of_coffee_tongue.svg`,
    `${imgUrl}game2_images/skin/pillow_skin.svg`,
    `${imgUrl}game2_images/eye/sun_eye.svg`,
    `${imgUrl}game2_images/nose/flower2_nose.svg`,
    `${imgUrl}game2_images/ear/man_talking_on_phone_ear.svg`,
    `${imgUrl}game2_images/tongue/icecream_tongue.svg`,
    `${imgUrl}game2_images/skin/stones_skin.svg`,
    `${imgUrl}game2_images/eye/lion_eye.svg`,
    `${imgUrl}game2_images/nose/perfume_nose.svg`,
    `${imgUrl}game2_images/ear/ambulance_ear.svg`,
    `${imgUrl}game2_images/tongue/cup_of_coffee_tongue.svg`,
    `${imgUrl}game2_images/skin/set_of_clothes_skin.svg`,
    `${imgUrl}game2_images/eye/moon_stars_eye.svg`,
    `${imgUrl}game2_images/nose/pizza_nose.svg`,
    `${imgUrl}game2_images/ear/speakers_ear.svg`,
    `${imgUrl}game2_images/tongue/mango_tongue.svg`,
    `${imgUrl}game2_images/skin/cotton_skin.svg`,
    `${imgUrl}game2_images/eye/aeroplane_eye.svg`,
    `${imgUrl}game2_images/skin/football_skin.svg`,
    `${imgUrl}game2_images/ear/dog_ear.svg`,
    `${imgUrl}game2_images/tongue/pop_corn_tongue.svg`,
    `${imgUrl}game2_images/skin/feather_skin.svg`,
    `${imgUrl}game2_images/eye/ice_cubes_eye.svg`,
    `${imgUrl}game2_images/ear/dog_ear.svg`,
    `${imgUrl}game2_images/skin/crayons_skin.svg`,
    `${imgUrl}game2_images/skin/dice_skin.svg`,
    `${imgUrl}game2_images/eye/moon_stars_eye.svg`,
    `${imgUrl}game2_images/tongue/cup_of_coffee_tongue.svg`,
    `${imgUrl}game2_images/eye/sun_eye.svg`,
    `${imgUrl}game2_images/tongue/glass_of_water_tongue.svg`,
    `${imgUrl}game2_images/eye/papers_eye.svg`,
    `${imgUrl}game2_images/eye/moon_stars_eye.svg`,
    `${imgUrl}game2_images/tongue/garlic_tongue.svg`,
    `${imgUrl}game2_images/skin/jug_of_water_skin.svg`,
    `${imgUrl}game2_images/eye/newspaper_eye.svg`,
    `${imgUrl}game2_images/skin/pencile_skin.svg`,
    `${imgUrl}game2_images/eye/tiger_eye.svg`,
    `${imgUrl}game2_images/eye/set_of_books_eye.svg`,
    `${imgUrl}game2_images/eye/set_of_books_eye.svg`,
    `${imgUrl}game2_images/eye/ice_mountain_eye.svg`,
    `${imgUrl}game2_images/skin/stones_skin.svg`,
    `${imgUrl}game2_images/eye/camp_fire_eye.svg`,
    `${imgUrl}game2_images/skin/pencile_skin.svg`,
    `${imgUrl}game2_images/nose/incense_stick_nose.svg`,
    `${imgUrl}game2_images/skin/shirt_skin.svg`,
    `${imgUrl}game2_images/skin/teddy_skin.svg`,
    `${imgUrl}game2_images/eye/sun_eye.svg`,
    `${imgUrl}audio_replay_button.svg`,
    `${imgUrl}layout_box_icon.svg`,
    `${imgUrl}layout_box_icon_green_highlight.svg`,
    `${imgUrl}layout_box_icon_red_highlight.svg`,
  ],

  sounds: [
    `${soundUrl}game2_sounds/sense_of_eye.mp3`,
    `${soundUrl}game2_sounds/sense_of_smell.mp3`,
    `${soundUrl}game2_sounds/sense_of_hearing.mp3`,
    `${soundUrl}game2_sounds/sense_of_taste.mp3`,
    `${soundUrl}game2_sounds/sense_of_touch.mp3`,
    `${soundUrl}correct_answer_game2.mp3`,
    `${soundUrl}wrong_answer_game2.mp3`,
    `${soundUrl}mouse_click.mp3`,
  ],

  lottie: [],

  select: ["Eye", "Nose", "Ear", "Tongue", "Skin"],
};

export default IntroMap;
