export const SceneMap = [
    {
        id: 1,
        prevSceneName: '/',
        currentSceneName: '/',
        nextSceneName: '/Scene5_1',
        hidePrev: true,
        hideNext: true,
        assetID: 'scene8',
    },
    {
        id: 2,
        prevSceneName: '/',
        currentSceneName: '/Scene5_1',
        nextSceneName: '/Scene5_2',
        hidePrev: true,
        hideNext: false,
        assetID: 'Scene5screen1',
    },
    {
        id: 3,
        prevSceneName: '/Scene5_1',
        currentSceneName: '/Scene5_2',
        nextSceneName: '/Scene5_3',
        hidePrev: false,
        hideNext: false,
        assetID: 'Scene5screen2',
    },
    {
        id: 4,
        prevSceneName: '/Scene5_2',
        currentSceneName: '/Scene5_3',
        nextSceneName: '/Scene5_4',
        hidePrev: false,
        hideNext: false,
        assetID: 'Scene5screen3',
    },
    {
        id: 5,
        prevSceneName: '/Scene5_3',
        currentSceneName: '/Scene5_4',
        nextSceneName: '/Scene5_5',
        hidePrev: false,
        hideNext: false,
        assetID: 'Scene5screen4',
    },
    {
        id: 6,
        prevSceneName: '/Scene5_4',
        currentSceneName: '/Scene5_5',
        nextSceneName: '/Scene5_6',
        hidePrev: false,
        hideNext: false,
        assetID: 'Scene5screen5',
    },
    {
        id: 7,
        prevSceneName: '/Scene5_5',
        currentSceneName: '/Scene5_6',
        nextSceneName: '/Scene7',
        hidePrev: false,
        hideNext: true,
        assetID: 'Scene5screen6',
    },
    {
        id: 8,
        prevSceneName: '/Scene5_6',
        currentSceneName: '/Scene7',
        nextSceneName: '/Game2Screen1',
        hidePrev: true,
        hideNext: true,
        assetID: 'scene7',
    },
    {
        id: 9,
        prevSceneName: '/Scene7',
        currentSceneName: '/Game2Screen1',
        nextSceneName: '/Game2Screen2',
        hidePrev: true,
        hideNext: true,
        assetID: 'Game2Trace1',
    },
    {
        id: 10,
        prevSceneName: '/Game2Screen1',
        currentSceneName: '/Game2Screen2',
        nextSceneName: '/Game2Screen3',
        hidePrev: true,
        hideNext: true,
        assetID: 'Game2Trace2',
    },
    {
        id: 11,
        prevSceneName: '/Game2Screen2',
        currentSceneName: '/Game2Screen3',
        nextSceneName: '/Game2Screen4',
        hidePrev: true,
        hideNext: true,
        assetID: 'Game2Trace3',
    },
    {
        id: 12,
        prevSceneName: '/Game2Screen3',
        currentSceneName: '/Game2Screen4',
        nextSceneName: '/WellDone',
        hidePrev: true,
        hideNext: true,
        assetID: 'Game2Trace4',
    },
    {
        id: 13,
        prevSceneName: '/Game2Screen4',
        currentSceneName: '/WellDone',
        nextSceneName: '/Game3Screen7',
        hidePrev: true,
        hideNext: true,
        assetID: 'WellDone',
    },

]